name: Run all Cypress Tests
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v4
     - name: Install Dependencies
       uses: cypress-io/github-action@v6.5.0
       with:
          working-directory: cypress
          command: yarn
     - name: Run Chrome Browser Cypress Tests
       if: success() || failure()
       uses: cypress-io/github-action@v6.5.0
       with:
          working-directory: cypress
          browser: chrome
          command: npm run cy:run_chrome
     - name: Run Edge Browser Cypress Tests
       if: success() || failure()
       uses: cypress-io/github-action@v6.5.0
       with:
         working-directory: cypress
         browser: edge
         command: npm run cy:run_edge
     - name: Run Electron Browser Cypress Tests
       if: success() || failure()
       uses: cypress-io/github-action@v6.5.0
       with:
         working-directory: cypress
         browser: electron
         command: npm run cy:run
    